### ISSUE TITLE
更多个性化

### ISSUE THREAD

**Issue by RayyyWW** [Samarium150/mirai-console-lolicon#1]
希望添加可以自定义冷却时间及自定义命令

**Comment by Samarium150** [comment]
可以细说一下想怎么自定义命令吗

**Comment by RayyyWW** [comment]
例如原本的/lolicon get [keyWord]
可以将/lolicon get指令简化/自定义
使他变短

**Comment by Samarium150** [comment]
明白了，但现在的实现方式不太支持自定义命令，加上mirai-console 2.0还没有正式发布，估计暂时不考虑这项功能
自定义冷却时间已经提上日程
