### ISSUE TITLE
fix: conflict with chat-command

### ISSUE THREAD

**Issue by LTHPKBTE** [Samarium150/mirai-console-lolicon#22]
1.开启此插件会导致chat-command插件的回馈全部变成双份(例如/help之后会发送两次帮助信息)
2.我就用了11次就显示api调用上限了...lolicon那边也不会显示调用历史，我也不知道是插件导致的还是api不行...

**Comment by Samarium150** [comment]
1. 上传一下截图
2. 没有apikey的话调用上限应该是10次/7200秒

**Comment by Samarium150** [comment]
补充: 插件应该是有调用历史在console里的
![image](https://user-images.githubusercontent.com/28302241/105759960-1c65f180-5f1f-11eb-8691-fee194c25381.png)

**Comment by Samarium150** [comment]
1. 已经复现, 会尽快处理

**Comment by LTHPKBTE** [comment]
重新看配置文件被重置成默认了...我重新加一下apikey用用试试

**Comment by LTHPKBTE** [comment]
![图片](https://user-images.githubusercontent.com/53574505/105761456-26730900-5f8e-11eb-8b20-4958b880dc32.png)
修改一下，不只是chat-command插件的回馈会变双份，mirai-console-lolicon请求失败的话也会请求两次(这是原本就有的功能吗？)

**Comment by Samarium150** [comment]
不是，bug的原因是设计这个插件时没有设计和chat-command一起使用的情况，所以mirai-console-lolicon自主实现了chat-command的一部分功能```commandListener = globalEventChannel().subscribeAlways()```

**Comment by Samarium150** [comment]
即mirai-console只有本插件的情况下也能在聊天环境执行命令
