### ISSUE TITLE
无法发送图片，只能发送文字

### ISSUE THREAD

**Issue by liaosunny123** [Samarium150/mirai-console-lolicon#30]
![image](https://user-images.githubusercontent.com/30096937/108022671-f46c3880-705b-11eb-8edf-6cfa353e0738.png)

**Comment by Samarium150** [comment]
请问Java版本是？

**Comment by liaosunny123** [comment]
1.8

**Comment by Samarium150** [comment]
更换成11应该就行了

**Comment by liaosunny123** [comment]
嗯，我刚刚用EpicMoMiraiG自带的环境检测也检测出是Java版本的问题了，他推荐安装15.0.2的java版本，谢谢了~没问题了我就来close issue

**Comment by Samarium150** [comment]
我顺便去更新一下文档

**Comment by liaosunny123** [comment]
如果可以的话不知道启动器能不能也推荐[EpicMoMiraiG](www.github.com/liaosunny123/epicmomiraig），目前Lolicon插件被插件中心收录可以一键下载安装，另外没问题了谢谢！

**Comment by Samarium150** [comment]
> 如果可以的话不知道启动器能不能也推荐[EpicMoMiraiG](https://www.github.com/liaosunny123/epicmomiraig)
> 目前Lolicon插件被插件中心收录可以一键下载安装，另外没问题了谢谢！

Linux版还在开发吧，我考虑考虑，感谢推荐

**Comment by liaosunny123** [comment]
是的，Linux还在适配开发，谢谢

**Comment by liaosunny123** [comment]
这个启动器是可视化启动，相比官方的和不知道启动器的人都友好很多，并且很多操作都支持直接可视化操作，非常方便.
