### ISSUE TITLE
在群内或私聊发送的指令无法识别

### ISSUE THREAD

**Issue by lingyun67** [Samarium150/mirai-console-lolicon#31]
在群内或私聊发送的指令无法识别，但是在控制台内发送的指令是可以直接运行的。
![IMG_20210226_113814](https://user-images.githubusercontent.com/64645371/109256084-36e9fe00-7830-11eb-9da2-1a8c351e4306.jpg)
是缺少了什么东西吗？

**Comment by Samarium150** [comment]
[前置条件](https://github.com/Samarium150/mirai-console-lolicon/wiki/Usage#prerequisites%E5%89%8D%E7%BD%AE%E6%9D%A1%E4%BB%B6)--[chat-command](https://github.com/project-mirai/chat-command/)
这个装了么

**Comment by aess-a** [comment]
少了[chat-command](https://github.com/pro- ject-mirai/chat-command)？

**Comment by lingyun67** [comment]
啊，第一次弄mirai，不知道要装这个前置
真的打扰了，感谢

**Comment by Samarium150** [comment]
解决了就好
