### ISSUE TITLE
对于调用API获取请求添加代理

### ISSUE THREAD

**Issue by LingMuXing** [Samarium150/mirai-console-lolicon#34]
在运用中好多请求由于网络问题导致调用失败，请求添加自定义代理。
get指令建议直接与插件激合指令合并
我看见可以保持图片至本地文件库未来是否要增加本地调用？
emmm好像问题有点多

**Comment by Samarium150** [comment]
1. 添加自定义代理和本地调用其实是有打算写的，只是最近太忙了没来得及
2. Get和什么合并？

**Comment by LingMuXing** [comment]
比如 要启动插件需要 （可自定义启动指令）lolicon  get其实感觉这是多余的。应该启动lolicon后面不带参数就调用图片API

**Comment by LingMuXing** [comment]
![54](https://user-images.githubusercontent.com/70338354/112298961-45fa8980-8cd2-11eb-8081-1e7fa1c042f1.png)
有个情况我不知道是我个人还是大多数 BOT 所有者账号添加进文件 重启插件依然不认。

**Comment by Samarium150** [comment]
> ![54](https://user-images.githubusercontent.com/70338354/112298961-45fa8980-8cd2-11eb-8081-1e7fa1c042f1.png)
> 有个情况我不知道是我个人还是大多数 BOT 所有者账号添加进文件 重启插件依然不认。

要在console关闭的情况下修改

**Comment by Samarium150** [comment]
> 比如 要启动插件需要 （可自定义启动指令）lolicon  get其实感觉这是多余的。应该启动lolicon后面不带参数就调用图片API
> 

你是说直接`/lolicon`就调用API吗

**Comment by LingMuXing** [comment]
> > 例如要启动插件需要（可自定义启动指令）lolicon get实际上感觉这是多余的。应该启动lolicon后面不带参数就调用图片API
> 
> 你是说直接`/lolicon`就调用API吗

是的，感觉这样要节省一点emmmm

**Comment by LingMuXing** [comment]
> > ![54](https://user-images.githubusercontent.com/70338354/112298961-45fa8980-8cd2-11eb-8081-1e7fa1c042f1.png)
> > 有个情况我不知道是我个人还是大多数BOT所有者账号添加进文件重新启动插件依然不认。
> 
> 要在console关闭的情况下修改

是的 我关闭了整个miari框架

**Comment by Samarium150** [comment]
> > > ![54](https://user-images.githubusercontent.com/70338354/112298961-45fa8980-8cd2-11eb-8081-1e7fa1c042f1.png)
> > > 有个情况我不知道是我个人还是大多数BOT所有者账号添加进文件重新启动插件依然不认。
> > 
> > 要在console关闭的情况下修改
> 
> 是的 我关闭了整个miari框架

仔细看了看你的截图，目前`master`只能填一个账号

**Comment by LingMuXing** [comment]
O(∩_∩)O谢谢
我看看
打扰了
