### ISSUE TITLE
请问该如何让图片反向代理也通过梯子呢

### ISSUE THREAD

**Issue by hisou** [Samarium150/mirai-console-lolicon#37]
图片是经过i.pixiv.cat拿取的，不过这个站点明显使用国外IP能更快下载完图片
我今天在服务器架设好clash之后，试验过梯子是正常的
不过用涩图命令的时候，图还是发出很慢，看梯子日志也没有打印去连接i.pixiv.cat的请求
请问要怎么办呢

**Comment by Samarium150** [comment]
我增加了一个配置文件来自定义代理，但不太能测试。
[测试版](https://samarium150.github.io/mirai-console-lolicon/assets/jars/mirai-console-lolicon-3.3.0.mirai.jar) 在这，更改`config/mirai-console-lolicon/ProxyConfig.yml` 里面的参数看看对你的梯子有没有效果

**Comment by hisou** [comment]
![2KPGD`F}{TUOBG)2098M75Y](https://user-images.githubusercontent.com/13644483/116072418-a3af3680-a6c1-11eb-8757-e5ac7a2808c0.jpg)
配置好后之后尝试指令，日志显示拒绝连接，图片文字和tag信息还会发出，之后的图片100%获取失败
![_)N6)XN _9LUYTBE9Y@}NZC](https://user-images.githubusercontent.com/13644483/116072984-61d2c000-a6c2-11eb-9470-b58b67bc2677.png)

顺便ProxyConfig.yml似乎重启bot就会恢复为默认值

**Comment by Samarium150** [comment]
配置文件要在console关闭的情况下修改，报的这个错应该是没连上你的代理

**Comment by hisou** [comment]
看来是成功了，已经看到下载进度。就是代理了也不快，不过是梯子的问题了
非常感谢

**Comment by Samarium150** [comment]
好的，我等会儿把这个版本发布，正式版应该没有那个进度条
