### ISSUE TITLE
请问能不能在撤回图片的时候把涩图简介一起撤回

### ISSUE THREAD

**Issue by 12123ads** [Samarium150/mirai-console-lolicon#41]

**Comment by Samarium150** [comment]
可以，下个版本提供这个选项

**Comment by 12123ads** [comment]
好的


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月8日(周六) 凌晨2:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Samarium150/mirai-console-lolicon] 请问能不能在撤回图片的时候把涩图简介一起撤回 (#41)




 
可以，下个版本提供这个选项
 
&mdash;
