### ISSUE TITLE
feat: blacklist and whitelist

### ISSUE THREAD

**Issue by Samarium150** [Samarium150/mirai-console-lolicon#47]
refer: [mirai forum](https://mirai.mamoe.net/topic/594/%E6%B6%A9%E5%9B%BEbot%E5%96%9C%E5%8A%A0%E4%B8%80-mirai-console-lolicon/8?_=1630573100209)

**Comment by kokorousaki** [comment]
想问下屏蔽某个群已经实现了吗，怎么配置呢

**Comment by Samarium150** [comment]
> 想问下屏蔽某个群已经实现了吗，怎么配置呢

1. `Config.yml`中的`mode`改成`blacklist`
2. `Data.yml`中的`groupSet`添加想屏蔽的群 **或者** 执行命令`/lolicon add group <群号>`

白名单模式下，只有`groupSet`中的群，`userSet`中的用户能执行`/lolicon get`和`/lolicon adv`这两个命令。
黑名单模式则反之。
