### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by 164ebr** [Samarium150/mirai-console-lolicon#57]
每个指令都来个权限节点吧

**Comment by Samarium150** [comment]
细说

**Comment by 164ebr** [comment]
就是只能群主跟群管理员能进行设置有点..

**Comment by 164ebr** [comment]
作为机器人主人在别的群里，没有权限这一说法。Umm

**Comment by 164ebr** [comment]
com.github.samarium150.mirai-console-lolicon
com.github.samarium150.mirai-console-lolicon.*
com.github.samarium150.mirai-console-lolicon.command
com.github.samarium150.mirai-console-lolicon.command.lolicon

**Comment by 164ebr** [comment]
不太希望r18功能被群主/管理员进行开关，cd，撤回等一些设置，只能由机器人管理员进行设置，应该咋办

**Comment by Samarium150** [comment]
> 作为机器人主人在别的群里，没有权限这一说法。Umm

当初设计的时候考虑到如果炸群了的话是由群主和管理员承担相应责任，所以没给机器人主人改本群设置r18设置的权限

**Comment by 164ebr** [comment]
原来如此 那算了

**Comment by 164ebr** [comment]
因为总是被拉进一些两个人的群，群主/机器人，滥用r18 ，没法管

**Comment by Samarium150** [comment]
> 因为总是被拉进一些两个人的群，群主/机器人，滥用r18 ，没法管

你可以点举报其实😂，顺便，白名单模式应该是只能由信任用户设置，所以设置之后就算被拉进群应该也不会响应名单之外的命令

**Comment by 164ebr** [comment]
原来如此

**Comment by CCYellowStar** [comment]
所以这个机制他不是主人就在所有群都是主人吗

**Comment by Samarium150** [comment]
> 所以这个机制他不是主人就在所有群都是主人吗

？机制是`master`如果在群里不是管理员或者群主不能使用`set`命令。如果不想在这个群使用的话，可以设置黑白名单

**Comment by CCYellowStar** [comment]
反正data那里还是可以改的

**Comment by Samarium150** [comment]
> 反正data那里还是可以改的

确实，你想炸群祸害群主和管理员谁也拦不住
