### ISSUE TITLE
容易误触发帮助菜单

### ISSUE THREAD

**Issue by Echoosx** [Samarium150/mirai-console-lolicon#58]
有的时候打“涩图” 会误触发机器人一大串的指令提示，不知道能不能自定义一下帮助菜单，或者直接把help关键词做的指令化一点

**Comment by Samarium150** [comment]
> 有的时候打“涩图” 会误触发机器人一大串的指令提示，不知道能不能自定义一下帮助菜单，或者直接把help关键词做的指令化一点

可以在`CommandConfig.yml`里把别名改了，不用`涩图`

**Comment by Echoosx** [comment]
确实，只不过有时候群友们会开玩笑，打一个“涩图 来两张”之类的，就会弹出一大串帮助菜单

**Comment by Samarium150** [comment]
> 确实，只不过有时候群友们会开玩笑，打一个“涩图 来两张”之类的，就会弹出一大串帮助菜单

因为`/`是可选，所以关键词被当成指令，如果要改的话大概只能把`/`是否可选加到config里面

**Comment by Echoosx** [comment]
不过那样的话其他的`get`之类的功能也会需要`/` ，还是算了吧

**Comment by Samarium150** [comment]
> 不过那样的话其他的`get`之类的功能也会需要`/` ，还是算了吧

对，就会变成`/涩图 来一张`

**Comment by Samarium150** [comment]
> 不知道自定义帮助菜单的话有没有可行性呢

实际上
```
参数不匹配, 你是否想执行: 
(/)lolicon add <type> <id>    (参数不足)
(/)lolicon 添加 <type> <id>    (参数不足)
# 此处省略
```
这部分是由mirai-console回复的，和插件没有关系

**Comment by Echoosx** [comment]
原来如此，也就是说Mirai-console把插件所有的命令拿过来之后，自动生成了一个帮助菜单
那就先这样吧

**Comment by CCYellowStar** [comment]
我是配合那个关键词撤回插件
