### ISSUE TITLE
feat: customize timeouts

### ISSUE THREAD

**Issue by WindsorMacmillan** [Samarium150/mirai-console-lolicon#78]
即使挂了网络代理，请求到i.pixiv.cat之后也经常会超时，而通过网页是可以正常访问i.pixiv.cat的图片地址的，只是个别图片加载时间比较长，所以希望能在配置文件中加入请求超时的自定义

**Comment by Samarium150** [comment]
`i.pixiv.re`会超时吗

**Comment by WindsorMacmillan** [comment]
会的，可能也和我所用的网络质量有关系，图片加载成功和超时基本上五五开（但实际上是一定都能加载出来的），超时限制能设置长一点就会好很多

**Comment by Samarium150** [comment]
请问抛出的错误是以下哪一个
- HttpRequestTimeoutException
- ConnectTimeoutException
- SocketTimeoutException

**Comment by WindsorMacmillan** [comment]
是SocketTimeoutException
