### ISSUE TITLE
指令/lolicon set r18有BUG

### ISSUE THREAD

**Issue by RayyyWW** [Samarium150/mirai-console-lolicon#8]
输入/lolicon set r18 0|1|2 即使输入任何数值也会返回“非法属性”

**Comment by Samarium150** [comment]
你是想说应该改成"输入的值非法”么

**Comment by RayyyWW** [comment]
![image](https://user-images.githubusercontent.com/31336504/103958492-171b4f80-5188-11eb-88d1-85bd690bdee5.png)

**Comment by Samarium150** [comment]
检查一下"1"后面是不是有空格

**Comment by Samarium150** [comment]
没事，我复现出来了，我检查一下是什么问题
