### ISSUE TITLE
求回答，如何在群内获取色图

### ISSUE THREAD

**Issue by FXDYJ** [Samarium150/mirai-console-lolicon#81]
在控制台执行指令
如：/lolicon get 東方Project
是可以得
但是在聊天中执行/lolicon get 東方Project，控制台没有任何输出，私信也不行
有chat-command-0.5.1插件

**Comment by Samarium150** [comment]
你需要手动分配权限，`/perm permit u<qq号> io.github.samarium150.mirai.plugin.mirai-console-lolicon:command.lolicon`
