### ISSUE TITLE
fix: correct verbose setting in forward mode

### ISSUE THREAD

**Issue by keysboy** [Samarium150/mirai-console-lolicon#83]
![image](https://user-images.githubusercontent.com/104134191/195632785-86732d76-cf09-4b58-b025-a8a7ca864845.png)
但他在控制台好像感觉是没问题的

**Comment by Samarium150** [comment]
如果私聊没问题就是tx的风控

**Comment by keysboy** [comment]
修改config里的配置好像重启mcl后自动重置了？（重启后复合命令别名的文件变回默认了...）还有个问题是设置verbose: false以后还是有图片信息...

**Comment by Samarium150** [comment]
> 修改config里的配置好像重启mcl后自动重置了？（重启后复合命令别名的文件变回默认了...）

你需要在console关闭的时候修改配置

> 还有个问题是设置verbose: false以后还是有图片信息...

这个我之后检查一下

**Comment by keysboy** [comment]
麻烦大佬了😊😊
