### ISSUE TITLE
没有权限

### ISSUE THREAD

**Issue by YCJ-GuLi** [Samarium150/mirai-console-lolicon#89]
### 问题描述

添加插件重启后执行help指令 提示我没有权限
2023-03-21 13:08:40 W/Lolicon: 权限不足. /lolicon 需要权限 io.github.samarium150.mirai.plugin.mirai-console-lolicon:command.lolicon
请问我该如何给予权限
![DMMXSN%KII6JWV@701 QMTC](https://user-images.githubusercontent.com/98393638/226523971-b0a7c682-9f22-4d2d-ac09-f86353312d97.png)

### 复现

重启之后使用也是这样

### mirai-console 版本

2.14.0

### 插件版本

6.0.8

**Comment by Samarium150** [comment]
`/perm permit u<qq> io.github.samarium150.mirai.plugin.mirai-console-lolicon:command.lolicon`

https://docs.mirai.mamoe.net/console/Permissions.html

**Comment by YCJ-GuLi** [comment]
谢谢你啦
